version: '3.8'

services:
  # Redis for URL frontier and state management
  redis:
    image: redis:7-alpine
    container_name: webcrawler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - webcrawler-network
    restart: unless-stopped

  # MongoDB for job management and persistent storage
  mongodb:
    image: mongo:6
    container_name: webcrawler-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: webcrawler
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - webcrawler-network

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: webcrawler-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_4LW_COMMANDS_WHITELIST: "ruok, conf, stat"
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    networks:
      - webcrawler-network
    restart: unless-stopped

  # Kafka for document streaming
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: webcrawler-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - webcrawler-network
    restart: unless-stopped

  # Kafka UI for monitoring (optional)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: webcrawler-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: webcrawler-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - webcrawler-network
    restart: unless-stopped
    profiles:
      - monitoring

  # Redis Commander for Redis monitoring (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: webcrawler-redis-commander
    depends_on:
      - redis
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - webcrawler-network
    restart: unless-stopped
    profiles:
      - monitoring

  # Main web crawler API server
  webcrawler-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webcrawler-api
    depends_on:
      - redis
      - kafka
      - mongodb
    ports:
      - "8089:8089"
    environment:
      # API Configuration
      API_HOST: 0.0.0.0
      API_PORT: 8089
      LOG_LEVEL: INFO
      
      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ""
      
      # Kafka Configuration
      KAFKA_BROKERS: kafka:29092
      OUTPUT_TOPIC: raw-documents
      ENABLE_KAFKA_OUTPUT: "true"
      ENABLE_LOCAL_SAVE: "false"
      
      # Crawler Configuration
      WORKERS: 3
      MAX_DEPTH: 3
      MAX_PAGES: 1000
      DEFAULT_DELAY: 1.0
      RESPECT_ROBOTS_TXT: "true"
      ALLOW_REDIRECTS: "true"
      
      # Allowed domains (comma-separated)
      ALLOWED_DOMAINS: "example.com,test.com,demo.org"
      
      # Python configuration
      PYTHONUNBUFFERED: 1
      
      # MongoDB Configuration
      MONGO_URI: mongodb://admin:password123@mongodb:27017/webcrawler?authSource=admin
    volumes:
      - ./logs:/app/logs
      - ./output:/app/crawler_output
    networks:
      - webcrawler-network
    restart: unless-stopped
    command: python api_crawler.py

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8089
    container_name: webcrawler-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8089
    depends_on:
      - webcrawler-api
    restart: unless-stopped
    networks:
      - webcrawler-network

volumes:
  redis_data:
  mongodb_data:
  zookeeper_data:
  zookeeper_logs:
  kafka_data:

networks:
  webcrawler-network:
    driver: bridge